---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring-grafana
spec:
  encryptedData:
    admin-password: AgCxlQMbA4qscqGS/SZzxArdk8DGULcAlmS+zWtfALgjv6p8U3czLVRhDc3pH6/wDLyLbgmbGa75hLmsofRO0cX4ttPC7fRy+TJOdA8YBVoo7louiMx20/8nDm5iowawJlA7GRk9n1bXqvwDQsQbXZ5d0iqA4fGg/lGGkJfiKhd7L5HtEvxsMZeQY3QFk36W/hrgrCx/MqowkRV4LTnx/HkHTtlFena8fzq+t0L2q0R4Z/ajLvIsrs8zoFKwA0gzyq8e4j/cD+VCmTe/oIBAU2g/4Rlt7FPW+bUKWTzMYOx1Lq2ve64oOHSwfsfnJxZ5SAIJcgQqEKH+dXR32a948FGwpD7oiOvmy89JUO/4ZU1vRqprb+37VT/2UCyGRhS61GBIcl8va+VhaEt2mnySQLMPOrztdp1N/1pBa9BJOJM7K7z2+WRzaS5fIfVuRAcgfr96+/cmkadi0tclnHxY8mJwPzpA6BakQ+39Xp5ozfJ/M8pgvGdqjXcs5Cc8glU44Q7eBkt1a4DWvRPSNJeqVq0IX4DNU9KptuEdScmzWX6uCPDzXe28ixuB6hsf7xz9lqx1FALVDfdakjPnljpLfvsktyWpKoovTBNDk5OR/WW4wHGs44WCZXFWeAiyZEc7Q+wrJyXivtZw3alKCLsC1e7fLPjgcZdiZsduF2eBSMgJKB/2d69mcdka22nffXs+yETVf7d4KSSj
    admin-user: AgAPROdsGIOctQCyNWMS2nmGU1jUm/Z+Mw88xhV5EANSuFy9jRaFjhlUjcC+TEOwxPR8zRYLFw8BTHMfP9uJNqM7a4uES4M/J/dnDscgljyQ+0tGm63pxRWnbTCdDNBJMNXo1XT8C/v8khbci6NjeXEgFl72PiUjgExnbsbejDAMNeujTZWTx0Sb7Mz3/KqWb4b9HO2IVbodARaHQo5AbZhjaKBq5lK0uVLsV4b2gdAzvohUa8lMIwN4JqR+/zZuXm1UyNC3rLDakIvvScX0ddWQcadkrsqF78uCDJCmMH8BIca7rYc6mzrshIYgiMX5Fp5V5Y3imcplPtFGxHg7AuKG4VeJO5jqsccZRDLcjL2hvz2ZGWDFKOmaMOSgKpRArfg4cta9NOxY/CXFUXki1skA0WBJrZQeoTgEzKtGrndnxPVnwgit3VDGpX37qoR/tMnExixXSB3rsHA4An2hHWTII9JB43V6FWFjAxF1NyLndZwZPhS/xmokDm1/wgfGYIk+Gbd8alcW0h6JFVqxRpKXGEd1K+SbO9rongajHmeJtHyRvLH8xx7n4EpC3Ob0/tVjUPVCd/UHTppEpdJmCnKasfpXNOaubbqq6FbXRF6BIbHhbSrUaPxdptbv8pvTxB+ZodN8inXfOnbFnnl2bXN0V6cxn8W4KzGmII0WJDJ1Tj796sPKiKUoJ6L5mjZ/I7StGCAF2A==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring-grafana
