---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDVIddUzmxe6rKBIW6atdzgDKdtTjR++tpeK6oOOv650ZYIP7Pb9o3vYRRVMXUhKVRpJWHFT9B8nwUcM0+/aQ2ghJTf2DwhWiUGLrcUH1bG9SfFETDj9Q/1gqOnU0BDGrngskrHZsGM/dere4Mif6Np58xEIwnXcU+ovmzOrog/Ggj+Mj63cTG7Ohn8lZD+JJZc4woiFc0UDqgLcAdZJSFQ6ezdJWQ+LcNCfQ+Vz47nOXVU2TFMMyVpo/uJZW0JNA18S87tKLarfR8uUVPDAiUN/g3C4+YRGI+j82oMcLiPQDneWSTKLe2qeiOVQEnUsgvqmW3Jfr8baUGInh4FzOTvkjCqhuUHb+VrhO6kGR3R4C5KUm5GFjGSvhLa/QiuvWmFxmnbJZ3a8/C2jNuNB6CCSFxtTS+UMNFKckoxxALCIzY/5U8JbQsnZVJIH8hDGeEp2xVZEdRxwGYIQwAew4EfXtHIwzli3K7AYFuOVtWtV8MVoa1YFvSQNWi4aIfJlwtzi9Gm/M+fV8z/3QwT8WLGcHNA8BnR0LxFRSZ71OgYUfzUmQfJfpNLbiUKDavUeMa14RRSRJf8heqidofKRd3LYSOVFDXnrUV8cAnDOOgU3ySXJIEEOMkou4/E0DdG9oFPRl6Nwa4nSJ/Bg82vdUf0WuMqFfoPwCouCwiGjNNEObObVryoJp9BgRGsgwE4xvK9mknkmPlX
    admin-user: AgA/r0+BRPtXjhtRiAERQB7avZRZ8b7YlJBEJFNGnYPlMSV6BbVbcamJwDSpXWvqpKm/Chwkg6dtjzZ+dGOzomlWSY4n9Ac86+a40J7WK4aIyxV9KaZNxsh7TdX98HIGmtojDHYaOLHcsnX0MgO3F5PClhbOK6fE6ghpItwbXo10cRqw0wV+/5mUAHfyTNTDCp3v+8VFof6UWg3uacgo8FfDsAukWlohMlGWQa3AdLqPGac3H+6YQzMECtIyY3HGwSHYMJ9+hteR1OwxL69nEmbL4WpOFYMLcC6OvNAQeFcJQmHjIa1ZLNfpnL3GuTNQ/TCa+UincTTaj4TSdeOwk9DEANTFH2gftbN8iBBz6YX8BY3x2q2lntgMMvHSNjp73BWDOcwaS1KBKEzBodzCMKm6y5AxwjpZo6vXqgnATgF91Kvu4vy79rp/VTxA1NU68mhegR48Lqr6dPmZ5D09zP6FXQO191ZMU7FR1Rt0mXX1WfaqRJxyOv4HB+D5RGUnmSOcZnJnoSd5ZFdDG6bgprcf3nlcWXOvUVBokSdnQLEm91YDc3zGmrPPeOxpHLhhUdTzjuCfnApP4nrnNM8lX7aS/Byfz47lBHXsFCsVeZwxUimYlpCNOKrnVyGswSP4EWeDyv75TvSISVY+QPcfCFUhuGtMsP+3G6TgX05QqNe0KYBLHaZq//5YjaT7P6YTftgkmEPmJw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
