---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC4weJOygdc/Z2dzO6mtKgvBKKRs6avowlp909nH3Hknjs9JigRZYPrkNozw8FI1BcSHjNKlbxM+hfnqprRCH+DR29U81xy14WBkbY6P5VeZisNsK4nIMccZzY36vLLRz42/tSUCYVR4JpcYuFWDUYuviYegVoypcrmlzUw4OjnKj0Ns/eQ6mwHIZMLg25FSclHWfQhTxNjoOj1GKZlfk6NJ7Doos0kHwo/PKicz3xmlw2nael6u5EDxvgl2zsjw7MqLTafpHgd5eMQ1oEVgZUcaqfSL5CDjsyjf6hAbJRS/NamRuwhP+i/RTouy7PsC8aGEyP6/Cl9xdD8KdC8SCkFiE1crKWOcuqPv7n4eMz/p8l/gcl9Cde+UQAQJ5oOp32OrrCKC+kSZe0FzSs1zYXLoXARD4f3ZDAxl+F9Gl1WSLl7vnC1BlhsJVwZb17pgDr/JYUReQE3aEIlsk61od5ltJcNgWrW9aK3LCPdtpiV5xMA7yPwSMUXP/Crq63VnJyYUOculoJlU5YVVeGTbiIGFXpvuzDH9+ESdTW6VkRU4CqSOOupW37L4hsD+qQgEs6q/s1ljFGs73wC4ntdZns0f2Ei/JHyltUpzA7JLSiAIiDZ/Kh6yY6u1BMP+c+t6c6AVRxZelqDK/Wi+p82aT/01xJp204wdtcX4P1LsQUJsHhr9wGcXw8HEVUv28JMl7BzPBf0ueio
    admin-user: AgA3DgdIVQV11zGgc29vQVSKfDFtk4rMssonSqM+ExUi7ZJJm+TYQ98kBij6D6j0YQSTF54H1NIePz8ztYfGoejZYwt8+LYu8GQRvWKzFKlMhJQ0NWJOa7AnYLfypBmNSgufhTxvkZFcegguwklqLlM7gFSoYG708AAFMzu9olzUTQQv+6l8lb/Vdb1Q2QLrxpoI6zIxHGRutvI6OkqY1tNZ8LhvXDPItX9odtFE8a8yBGdO+REjoP62wm+jNDUvwuVmJjK3uLBzny/dPkNaABKNVsSiP+qQPzRUltkwJPYjs+N3cQcT893xeMn/Cu6d+idMxDdWUrw2qG/d1AntLuJws6GK9WTDMadrbP3xPRi60HpNkUiojHcQAwP7jNM3VSOs4KbSMxB2oZUU2OAc4tO/VH7aMUWTH4MoRPFOjg1o5Pcci2sb5mkSEubyrecZ5CvWIWFZ5/34pnBcMN7jN2CseJvEJjArZhjqwd8nMtYlAz4jqHxPxiaJQV/ZKmPqfU6AojlAOoV3/XuClRRFsGZ6vQarJ2fdFS24DZdPwbVxXJ+3BwPZrWtsz83NMBAp/u4Pw2v2J35XAKSfwq9Y1CpDGSw9l0llBI/xOoUwiprTb2IkUFknkBtWJ2962CqqL/xGaZrVkNUHSP0FCVA1FRSE/Hyqp1sLBECLaK5+RingoZ/Uh7pl5258Mt/mgFLfVglFSeosZw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
