---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring-grafana
spec:
  encryptedData:
    users: AgBGqGzOC5nQ0QRWWI2X6LCB4e8EBDzjkzCH/X+UMss/SwiiRKdjvOsUkGa+h02e6KoH8q4wRwXPF8/KI1emEVs6O4HUjSZv9rXYl18epVTOBLYSgC25TyAKk/uuJGBpNuAS1VH5/x7hMoqIka9jKdqKePAOM93NMetKnAHDNkzsSNzsW0PUk3ujPHrF6p/xgT3qQppbGl+nenep8T2rBx9B0mLLnvGvdotTMxrFV6SBR8sj2hBbjTu5kJJkjnZmf30s/8G32wOrzf6oy8sEngfHPlyKrelUOZr12ICaXMyxNuYFvjlqDVUs8lH2Q6jItSL4GC5SefqYvSb76jV0mUPed5qrOHrCHjOG67zo2VgIthwfLXKdKKHClaRGJ0esYF9Ru6VuGjCGQauR1CE/f4LfXLQD0qB5wJgz4LkROI2ZqUOYcE1TeRbKI4wNywvuhBempaDGf/osEdb09Tt+YRzkqX+LZxslQiDUM6JH/vAf10mFM4rK+ZwLvReJN+C1hF7EjM0rhsXw06KwMf6gvkbwM9XUavmfxm69yfWNAEJDHM3d6DAsxVfdLthdnPeO6V2xCeEcWpjpGXHD//mprcX+4IKfEKopYM7gTI03AbXEy181HTgVvkXJp8khWQoCKEcCUB7FF/HHRU6sorIzL3OWVFWlOZyuisdTNCUuQkCFTKA8ucTlWVnjBGnXogLt4YJqYSIN5AiSGK8ZVg2LuovMHxOLMoiUdNzpSRJ2UX2PCm1OdfZnBbrwVrnTDsardeli8MviKSRy8tGyDBkrZfCCC6k=
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: monitoring-grafana
