---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgCROKRysmIUCaiuNLXoH9Nwm95rhPXNIc+z28Ku1CabzUmsM1v0CFU9Tn+Fc5ELw9JWz+iGuODj8Gbpq3dL/Ri+EkdP1IghN6CKLMYCp2e4TTTLElckqfJbbv4S7KJ9Eu4BREw7SbvaNWenSfGiRt96P71PHAl719Kv4xD26MD13bas+TLWm2c4ZlvjDExhZoaMkGyoCMYP5r4qrSR0+XtyfqugWvirAprxN/IIyF7307QsMl0MPPsr6JgIZSIoOyFNvdbUntDUwrEPau8sSBOMazF3cisCQlmt6rcPeRiQ+y1b3V74v8oamzWIeqYQwZWmiZXUwV/QxRlOdrXlA7Xzk9ZZeLinjwEwW5M5cjZssNGDUizwj9UIuoFbmYs866PMDJZEq1oGjFpbqsqFWb4KLoFGW2pf9phcGGQ3iSKcBzwxgaaljjYkGWB/N4Ti5GLlHY3tHENZt+HiGOgU1GGiMAx3gmzdNfGQtX7Wbhb5iMzbQ5eCq6HIzqxcQy1W4DKmIvt8ljUzwSy0hzq2mWTitj/RQCTS0bMdBygYMEZDnPCQHCGD0GPxlDFf6+AuBUqxjRDzd9W+56HEJFeah2mnUIO+9uz3+yn5vDBVVVkS6LwiRMsjJ1y/e04pgVZ5z4dBaed8nTvp7gdzprF13zztnqDVGmgZtoQnvLIL53FnQ1J8Kaee4lF7gC+EmwqFyZ/QKA35BBNBvE3Mxl4mKjdDm0uLHtqG4T2X/T5N67Cv0c3ActBmesCdCtDoaA9DrB76biG7Wr1Cnd8H/0CWzSpfdkk=
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: monitoring
