apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring-grafana
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prom.phink8s.com`)
      kind: Rule
      # middlewares:
      #   - name: basic-auth-prometheus   # see middleware below
      #     namespace: monitoring-grafana
      services:
        - name: monitoring-grafana-kube-pr-prometheus
          port: 9090
  tls:
    secretName: wildcard-phink8s.com-tls