{
 "title": "VPN Status",
 "refresh": "5m",
 "panels": [
  {
   "title": "VPN Status",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpn_check_status", "legendFormat": "VPN" }
   ]
  },
  {
   "title": "VPN Check API",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpn_check_api_error", "legendFormat": "VPN API" }
   ]
  },
  {
   "title": "Public IP Check",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpn_check_public_ip_error", "legendFormat": "Public IP" }
   ]
  },
  {
   "title": "Metrics Age",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpn_check_metrics_age_seconds", "legendFormat": "Age" }
   ]
  },
  {
   "title": "Public IP",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpn_check_public_ip", "legendFormat": "{{`{{ address }}`}}" }
   ]
  },
  {
   "title": "VPN IP",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpn_check_vpn_ip", "legendFormat": "{{`{{ address }}`}}" }
   ]
  },
  {
   "title": "VPN Status Over Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    { "expr": "vpn_check_status", "legendFormat": "VPN Connected" }
   ]
  },
  {
   "title": "VPN API Response Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "vpn_check_duration_seconds", "legendFormat": "Response Time" }
   ]
  }
 ]
}